#!/bin/sh

# Useful global variables

HOMEBREW_PREFIX="/usr/local"
DEV_CONFIGS_ROOT=$HOME/.dev-configs

##
#
# Setup dev configs
#
##

# Install vundle for vim plugin management.
rm -rf $HOME/.vim/bundle/Vundle.vim
git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim

# Link vim settings.
echo "Linking vimrc"
rm $HOME/.vimrc
ln -s $DEV_CONFIGS_ROOT/vim/.vimrc $HOME/

# Link bash_profile
echo "Linking bash_profile"
rm $HOME/.bash_profile
ln -s $DEV_CONFIGS_ROOT/bash/.bash_profile $HOME/.bash_profile

# Link bash_profile dependencies
rm $HOME/.dotfiles/*
mkdir $HOME/.dotfiles/
ln -s $DEV_CONFIGS_ROOT/bash/dotfiles/* $HOME/.dotfiles/

# Link gitconfig
echo "Linking gitconfig"
rm $HOME/.gitconfig
ln -s $DEV_CONFIGS_ROOT/git/.gitconfig $HOME/.gitconfig

# Link global gitignore
echo "Linking global gitignore"
rm $HOME/.gitignore_global
ln -s $DEV_CONFIGS_ROOT/git/.gitignore_global $HOME/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global

##
#
# Install useful tools
#
##

# More code borrowed from thoughtbot: https://github.com/thoughtbot/laptop/blob/master/mac#L49
# Install homebrew
if [ -d "$HOMEBREW_PREFIX" ]; then
	if ! [ -r "$HOMEBREW_PREFIX" ]; then
		sudo chown -R "$LOGNAME:admin" /usr/local
	fi
else
	sudo mkdir "$HOMEBREW_PREFIX"
	sudo chflags norestricted "$HOMEBREW_PREFIX"
	sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

if ! command -v brew >/dev/null; then
	echo "--------------------"
	echo "| Installing brew. |"
	echo "--------------------"
	if uname | grep Darwin; then
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi
fi

if brew list | grep -Fq brew-cask; then
	echo "--------------------------------------"
	echo "| Uninstalling old Homebrew-Cask ... |"
	echo "--------------------------------------"
	brew uninstall --force brew-cask
fi
brew tap 'homebrew/bundle'
brew tap 'caskroom/cask'
brew update

# Install cmake – required for YouCompleteMe
brew install cmake

# System python causes issues with vim.
if [ -z $(brew list | grep python@2) ]; then
  brew install python@2
fi

vim +'PlugInstall --sync' +qa

cd ~/.vim/plugged/YouCompleteMe/
python install.py
cd -
