#!/bin/bash

clear_node_deps() {
  for dir in ./*; do
    if [[ -d "$dir/node_modules" ]]; then
      echo "Removing contents of $dir/node_modules"
      rm -rf $dir/node_modules/
    fi
  done
}

uuid() {
  if [[ -z "$1" ]]; then
    echo "Requires on argument, the number of bytes you want your key to be"
    return
  fi
  date +%s | sha256sum | base64 | head -c $1 ; echo
}

archive() {
  if [ -z $1 ]; then
	echo "must provide an argument"
	return 1
  fi

  if [ ! -f $(pwd)/$1 ] && [ ! -d $(pwd)/$1 ]; then
	echo "file/directory does not exist"
	return 1
  fi

  if [ ! -d $HOME/code/.archive ]; then
	mkdir -p $HOME/code/.archive
  fi

  archived=$(pwd)/$1
  mv $archived $HOME/code/.archive/

  echo "moved $1 to .archive directory"
  echo "to undo run the command: ~$ mv $HOME/code/.archive/$1 $archived"
}

timestamp() {
  echo $(date +%Y%m%d-%H%M)
}

set_main_branch() {
  if [ -d .git ]; then
    export GIT_MAIN=$(git remote show origin | grep "HEAD branch" | sed 's/.*: //')
  fi
}

cd() {
  builtin cd "$@"

  set_main_branch
}

